### PR TITLE
Do not activate on startup, activete on gistpad view

### PR DESCRIPTION
**Pull request by carlocardella**
**This PR fixes Issue#**
Addresses #253

**Description of the PR**:
Do not activate on startup, activate onView gistpad

### CODE REVIEW

**Comment by lostintangent** [comment]
Since we contribute a bunch of command palette commands (e.g. new gist, open gist), that a user could use, without needing to open the GistPad tab, we'd also need to add those as activation events as well.

And there's also a URI handler that would need to be added.

**Comment by carlocardella** [comment]
Thanks, I have added them. 
I could not find the `Focus on...`, I assume those are injected by VSCode? 

image

Also, out of curiosity, this means the uriHandler does not work for Insiders, right? Likely not a big problem, but I do have a machine where I use Insiders only, Stable is not installed

https://github.com/carlocardella/gistpad/blob/b539d0d83502b32c0554f6b30536cbbfc7bf8f88/src/uriHandler.ts#L87-L89
```typescript
export function createGistPadOpenUrl(gistId: string) {
  return `vscode://${EXTENSION_ID}${OPEN_PATH}?${GIST_PARAM}=${gistId}`;
}
```

**Comment by lostintangent** [comment]
> I could not find the `Focus on...`, I assume those are injected by VSCode? 

Yep. Those are managed by VS Code, and would trigger the view-based activation handlers.

> Also, out of curiosity, this means the uriHandler does not work for Insiders, right? Likely not a big problem, but I do have a machine where I use Insiders only, Stable is not installed

The URI handler supports stable and insiders. But the logic for generating a URI from within GistPad, only creates stable-based URIs (since that's what the majority of users use). But if you manually tweaked that URI to point at insiders, it would work.

**Comment by lostintangent** [comment]
I just realized that this change would break the status bar buttons we add, when a user has a wiki repository ([details](https://github.com/lostintangent/gistpad#pages)). There are definitely users that use/rely on this, and so I'm not really sure it's worth breaking it. It would be annoying to have to run a command or focus a view, in order for these to appear. Particularly since they're meant to be used from any context, to take notes throughout your day.

I think there's still value in being explicit about our activation events, and so I like this change. But we should add also "onStartupFinished" to the list, so that we still activate on startup.

**Comment by carlocardella** [comment]
Makes sense, but I that case do we still need all other events? If we activate onStartupFinished then the other events (except onUri) would never be really used?

**Comment by carlocardella** [comment]
Uhm... I guess unless a user has really a lot of extensions installed and they startup takes a long time, in which case they could manually trigger une of the activation commands before `onStartupFinisced`. Ok, I'm going to add it

**Comment by lostintangent** [comment]
Yep exactly. You could easily run a command, or launch the URI handler, before startup has finished. Plus, I think it's nice to have the explicit list of required acquired events, in the event that we need to reconsider these again in the future.

**Review by lostintangent — APPROVED** [review]

**Comment by lostintangent** [comment]
Just to confirm: are you still planning to add the onStartupFinished event? We'd need that as the ultimate fallback, in order to support the status bar buttons.

**Comment by carlocardella** [comment]
My bad, sorry, I thoguht I did

**Pull request merged**
