### PR TITLE
Fix to sync followed users across devices

### PR DESCRIPTION
**Pull request by carlocardella**
**This PR fixes Issue#**
#291

**Description of the PR**:
Fix to sync followed users across devices

### CODE REVIEW

**Comment by carlocardella** [comment]
This was easier than I though

Followed users:
https://github.com/lostintangent/gistpad/blob/6bc4667eb00c09c81a852231b2f7144b86def053/src/store/storage.ts#L32-L34

Repositories:
https://github.com/lostintangent/gistpad/blob/6bc4667eb00c09c81a852231b2f7144b86def053/src/repos/store/storage.ts#L13-L15

Also, while we are on this: I see we are sorting Followed users but not repos, is that ok or should we sort repos too?

**Comment by lostintangent** [comment]
I'm confused why this would fix things? Is the actual compiled code different?

**Comment by carlocardella** [comment]
I did not check the compiled Javascript (not at my desk at the moment), but the fix looks like what we have for Repositories. 
`get<string[]>` was throwing a silent exception, visible only running that line in the debug console

**Comment by lostintangent** [comment]
Interesting. Does that mean that repos were already being synced then?

**Comment by carlocardella** [comment]
Yes, reps are synced but I need to manually refresh the list to see the new ones added on another machine. I was expecting them to show up automatically which is what made me think repos were not being synced.

**Comment by carlocardella** [comment]
It may be possible to automatically refresh the tree upon sync: when other controls are moved around in the UI the change is reflected automatically across all my machines.

**Comment by lostintangent** [comment]
Ah interesting. Yeah I'm not aware of a way to detect that globalState has been updated. VS Code probably auto-updates UI state that it manages the syncing for, and an extension could detect if settings were changed as a result of syncing. But I'm not sure if there's an API for extensions to detect globalState changes currently?

**Comment by carlocardella** [comment]
No idea but it sounds like a fun investigation 😊

**Comment by carlocardella** [comment]
If you are ok with this small change, we could merge it and create a new release (I think there is more more change already in master waiting to be released) and I can investigate the automated refresh separately

**Comment by lostintangent** [comment]
Yep! Works for me

**Pull request merged**
